; PlatformIO Multi-Project Workspace
; Build with: pio run -e remote  or  pio run -e robot

[platformio]
default_envs = remote

[env]
framework = arduino
platform = atmelsam
board = adafruit_feather_m0

[env:remote]
src_dir = remote
lib_extra_dirs = remote/../lib

[env:robot]
src_dir = robot
lib_extra_dirs = robot/../lib
